prgrms-be-devcourse/NBE3-4-2-Team13

- backend/src/main/java/com/app/backend/domain/post/controller/PostController.java
- backend/src/main/java/com/app/backend/domain/post/entity/Post.java
- backend/src/main/java/com/app/backend/domain/post/entity/PostStatus.java
- backend/src/main/java/com/app/backend/domain/post/exception/PostErrorCode.java
- backend/src/main/java/com/app/backend/domain/post/exception/PostException.java
- backend/src/main/java/com/app/backend/domain/post/repository/PostRepository.java
- backend/src/main/java/com/app/backend/domain/post/repository/PostRepositoryCustom.java
- backend/src/main/java/com/app/backend/domain/post/repository/PostRepositoryImpl.java
- backend/src/main/java/com/app/backend/domain/post/service/PostService.java
- backend/src/main/java/com/app/backend/global/config/SecurityConfig.java
- 게시글 Domain 기본 틀 구성
- security 기본 설정 및 h2-console 허용
#3 이슈와 연결
> [FEATURE]: [BE] Post 도메인 기본 설정

- backend/src/main/java/com/app/backend/global/entity/BaseEntity.java
- BaseEntity 내 disabled 필드 초기화 누락으로 인한 에러
- Boolean disabled; -> Boolean disabled = false; 수정
> [FIX]: [BE] BaseEntity 내 disabled 필드 초기화 누락 수정

- .idea/.gitignore
- .idea/NBE3-4-2-Team13.iml
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/dto/CommentDto.java
- backend/src/main/java/com/app/backend/domain/comment/entity/Comment.java
- backend/src/main/java/com/app/backend/domain/comment/exception/CommentErrorCode.java
- backend/src/main/java/com/app/backend/domain/comment/exception/CommentException.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepository.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
Comment 기본 구조 세팅
Comment에 필요한 컨트롤러, 서비스, 예외, 리포지터리, dto, 엔티티
> [FEATURE] : [BE] Comment 기본 설정

- .idea/dataSources.xml
- .idea/encodings.xml
- backend/src/main/java/com/app/backend/domain/category/controller/CategoryController.java
- backend/src/main/java/com/app/backend/domain/category/dto/CategoryDto.java
- backend/src/main/java/com/app/backend/domain/category/entity/Category.java
- backend/src/main/java/com/app/backend/domain/category/repository/CategoryRepository.java
- backend/src/main/java/com/app/backend/domain/category/service/CategoryService.java
- 카테고리 엔티티 및 기본 구조 추가
- exception, dto 추후에 작성하겠습니다..^_^
> [Feature] : [BE] 카테고리 기본 구조 및 엔티티 추가

- backend/src/main/java/com/app/backend/domain/group/controller/GroupController.java
- backend/src/main/java/com/app/backend/domain/group/entity/Group.java
- backend/src/main/java/com/app/backend/domain/group/entity/RecruitStatus.java
- backend/src/main/java/com/app/backend/domain/group/exception/GroupErrorCode.java
- backend/src/main/java/com/app/backend/domain/group/exception/GroupException.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepository.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryCustom.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryImpl.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupService.java
- backend/src/test/java/com/app/backend/domain/group/repository/GroupRepositoryTest.java
- 모임(Group) 엔티티 구현 및 기본 패키지 구조/예외 추가
- 모임(Group) 엔티티, 리포지토리/서비스/컨트롤러 추가
- 예외(GroupException), 예외 코드(GroupErrorCode) 추가
- 리포지토리 테스트 추가
> [FEATURE]: [BE] 모임(Group) 엔티티 및 기본 구조 추가

- backend/src/main/java/com/app/backend/domain/group/entity/Group.java
- backend/src/test/java/com/app/backend/domain/group/repository/GroupRepositoryTest.java
- @Builder 생성자 적용
- GroupRepository 테스트 내 Group 생성 패턴 수정
> [FIX]: [BE] 모임(Group) 엔티티 생성자 수정

- backend/src/main/java/com/app/backend/domain/category/controller/CategoryController.java
- backend/src/main/java/com/app/backend/domain/category/dto/CategoryPageDto.java
- backend/src/main/java/com/app/backend/domain/category/repository/CategoryRepository.java
- backend/src/main/java/com/app/backend/domain/category/service/CategoryService.java
- backend/src/test/java/com/app/backend/domain/category/controller/CategoryControllerTest.java
#24 
- 카테고리 조회 기능
- 카테고리 조회 기능 (페이징 방식)
- 컨트롤러 테스트 작성 (생성 + 조회)
> [Feature]: [BE] 카테고리 조회 기능 + 컨트롤러 테스트

- backend/.gitignore
- backend/src/main/java/com/app/backend/domain/category/controller/CategoryController.java
- backend/src/main/java/com/app/backend/domain/category/dto/CategoryReqBody.java
- backend/src/main/java/com/app/backend/domain/category/entity/Category.java
- backend/src/main/java/com/app/backend/domain/category/exception/CategoryErrorCode.java
- backend/src/main/java/com/app/backend/domain/category/service/CategoryService.java
- backend/src/test/java/com/app/backend/domain/category/controller/CategoryControllerTest.java
#26 
- 카테고리 수정 기능
- 카테고리 수정 기능
- 테스트 코드 작성 (모두 통과)
> [Feature]: [BE] 카테고리 수정 기능

- backend/src/main/java/com/app/backend/domain/member/controller/KakaoController.java
- frontend/src/app/ClientLayout.tsx
- frontend/src/app/ClientPage.tsx
- frontend/src/app/member/me/ClientPage.tsx
- frontend/src/lib/auth/token.ts
- frontend/src/lib/business/components/LoginButton.tsx
- frontend/src/middleware.ts
- frontend/src/stores/auth/loginMember.tsx
- #40 
- 샘플 코드에서 카카오 로그인 부분 수정
- 샘플 코드에 불필요한 파일들이 너무 많아서 정리가 필요함. 일요일에 정리할 예정.
- 백엔드 쪽 코드는 샘플이고, 호남님이 수정하시면 다시 push 할 예정.
> [Feature]: [FE] 카카오 로그인

- backend/src/main/java/com/app/backend/domain/member/oauth/OAuth2SuccessHandler.java
- backend/src/main/java/com/app/backend/domain/member/service/CustomOAuth2UserService.java
- backend/src/main/java/com/app/backend/domain/member/service/KakaoAuthService.java
- backend/src/main/java/com/app/backend/global/config/SecurityConfig.java
- backend/src/main/resources/config/application-dev_auth.yml
- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/api/auth/kakao/callback/page.tsx
- frontend/src/lib/backend/client.ts
#	backend/src/main/java/com/app/backend/domain/member/controller/KakaoController.java #	frontend/src/lib/business/components/LoginButton.tsx
- UI 에서 카카오 로그인 클릭시 발생한 에러 수정
> [Refactor] 카카오 로그인 코드 수정

- backend/src/main/java/com/app/backend/domain/member/controller/ApiMemberController.java
- backend/src/main/java/com/app/backend/domain/member/dto/request/MemberJoinRequestDto.java
- backend/src/main/java/com/app/backend/domain/member/jwt/JwtProvider.java
- backend/src/main/java/com/app/backend/domain/member/service/KakaoAuthService.java
- backend/src/main/java/com/app/backend/domain/member/service/MemberService.java
- backend/src/test/java/com/app/backend/domain/member/MemberControllerTest.java
- 관리자 Role 을 가진 사람만 모든 회원이 조회될 수 있도록 구현
> [Feature] : [BE] 관리자의 모든 회원 조회

- backend/src/main/java/com/app/backend/domain/group/entity/GroupMembership.java
- backend/src/main/java/com/app/backend/domain/group/entity/MembershipStatus.java
- backend/src/main/java/com/app/backend/domain/group/exception/GroupMembershipErrorCode.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupMembershipRepository.java
- backend/src/test/java/com/app/backend/domain/group/repository/GroupMembershipRepositoryTest.java
- GroupMembershipRepository 메서드 추가
- 회원 상태(MembershipStatus), 회원 권한(GroupRole)에 따른 엔티티 수  조회 메서드 추가
- 테스트 코드 추가
- GroupMembershipErrorCode 추가
- GroupMembership  엔티티 내 수정 메서드 추가
> [Feature]: [BE] GroupMembership 엔티티 조회 관련 메서드 추가 등

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/dto/CommentDto.java
- backend/src/main/java/com/app/backend/domain/comment/dto/request/CommentCreateRequest.java
- backend/src/main/java/com/app/backend/domain/comment/dto/response/CommentResponse.java
- backend/src/main/java/com/app/backend/domain/comment/entity/Comment.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
- 댓글 추가 기능
- 테스트 코드 통과
- 댓글 추가 기능
- dto를 요청과 응답으로 구분함
- 엔티티 수정
- 댓글 추가 기능 테스트 코드
#21
> [Feature]: [BE] 댓글 추가

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/entity/Comment.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepository.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
- 댓글 삭제 기능
- 댓글 작성한 것을 삭제한다.
- 댓글 작성자만 댓글을 삭제할 수 있다.
- 테스트 코드 통과
> [Feature]: [BE] 댓글 삭제

- backend/src/main/java/com/app/backend/domain/chat/room/controller/ChatRoomMemberController.java
- backend/src/main/java/com/app/backend/domain/chat/room/dto/response/ChatRoomListResponse.java
- backend/src/main/java/com/app/backend/domain/chat/room/dto/response/ChatRoomResponseMessage.java
- backend/src/main/java/com/app/backend/domain/chat/room/repository/ChatRoomRepositoryCustom.java
- backend/src/main/java/com/app/backend/domain/chat/room/repository/ChatRoomRepositoryImpl.java
- backend/src/main/java/com/app/backend/domain/chat/room/service/ChatRoomService.java
- backend/src/test/java/com/app/backend/domain/chat/room/controller/ChatRoomMemberControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/room/service/ChatRoomServiceTest.java
> [Feature]: [BE] 멤버가 참여하고 있는 모임 채팅방 조회

- backend/src/main/java/com/app/backend/domain/post/dto/req/PostReqDto.java
- backend/src/main/java/com/app/backend/domain/post/service/PostService.java
- backend/src/test/java/com/app/backend/domain/post/controller/PostControllerTest.java
- backend/src/test/java/com/app/backend/domain/post/service/PostServiceTest.java
- 기존 게시글 CRUD기능에 Membership 검증 추가
- 검증 로직 testcode 작성
-  기존 코드 구조 일부 수정
> [Feature]: [BE] 게시글 접근 권한 Membership 검증 로직 추가

- backend/src/main/java/com/app/backend/domain/category/entity/Category.java
- backend/src/main/java/com/app/backend/domain/category/repository/CategoryRepository.java
- backend/src/main/java/com/app/backend/domain/group/controller/GroupController.java
- backend/src/main/java/com/app/backend/domain/group/dto/request/GroupRequest.java
- backend/src/main/java/com/app/backend/domain/group/dto/response/GroupResponse.java
- backend/src/main/java/com/app/backend/domain/group/entity/Group.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepository.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryCustom.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryImpl.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupService.java
- backend/src/test/java/com/app/backend/domain/group/controller/GroupControllerTest.java
- backend/src/test/java/com/app/backend/domain/group/repository/GroupRepositoryTest.java
- backend/src/test/java/com/app/backend/domain/group/service/GroupServiceTest.java
- backend/src/test/java/com/app/backend/domain/group/supporter/SpringBootTestSupporter.java
- 모임-카테고리 간 1:N 연관관계 설정 추가
- 모임 엔티티 내 카테고리 수정 메서드 추가
- 모임 생성/수정 로직 내 카테고리 엔티티 조회 로직 추가
- 모임 응답 DTO 내 필드 2개 추가: 카테고리명, 현재 모임 내 가입 회원 수(APPROVED)
- 테스트 코드 추가/수정
> [Feature]: [BE] 카테고리-모임 연관관계 추가 등

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/entity/Comment.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
#69 
- 댓글 수정
- 댓글 테스트 코드
- 작성된 댓글을 조회하고 수정할 수 있다.
- 댓글 작성 테스트 코드 통과
> [Feature]: [BE] 댓글 수정

- backend/src/main/java/com/app/backend/domain/category/controller/CategoryController.java
- backend/src/main/java/com/app/backend/domain/category/service/CategoryService.java
- 카테고리 ResponseStatus 어노테이션 추가
- 카테고리 서비스 중복 코드 제거
> [Feature]: [BE] 카테고리 ResponseStatus 어노테이션 추가

- backend/src/main/java/com/app/backend/domain/member/controller/ApiMemberController.java
- backend/src/main/java/com/app/backend/domain/member/controller/KakaoController.java
- backend/src/main/java/com/app/backend/domain/member/exception/MemberErrorCode.java
- backend/src/main/java/com/app/backend/domain/member/jwt/JwtProvider.java
- backend/src/main/java/com/app/backend/domain/member/service/MemberService.java
- backend/src/main/java/com/app/backend/domain/member/util/CommonUtil.java
- backend/src/main/java/com/app/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/app/backend/global/config/TestConfig.java
- backend/src/test/java/com/app/backend/domain/member/MemberControllerTest.java
- backend/src/test/java/com/app/backend/domain/member/TestConfig.java
- 로그아웃 시 토큰 무효화 기능 구현
- 토큰 쿠키 관련 기능을 별도 클래스로 분리
- 테스트 Mocking 에 필요한 Test Config 추가
> [Feature] : [BE] 로그아웃, TestConfig

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/dto/response/CommentResponse.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepository.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
- 게시물에 대한 댓글 조회
- 응답에 닉넴임을 추가하여 사용자 id 뿐만 아니라 닉네임도 볼 수 있도록 함
- 페이징으로 댓글들이 조회된다.
- 댓글 조회 테스트 통과
> [Feature]: [BE] 댓글 조회

- backend/src/main/java/com/app/backend/domain/meetingApplication/controller/MeetingApplicationController.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/dto/MeetingApplicationListDto.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/exception/MeetingApplicationErrorCode.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/repository/MeetingApplicationRepository.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/service/MeetingApplicationService.java
- backend/src/test/java/com/app/backend/domain/meetingApplication/meetingApplicationControllerTest/MeetingApplicationControllerTest.java
- meeting application 리스트 조회
- meeting application 상세 조회
- 컨트롤러 테스트 작성
- 서비스 테스트는 추후 작성 예정
- meeting application 리스트 조회 기능
- meeting application 상세 조회 기능
- 컨트롤러 테스트 작성(통과)
> [Feature]: [BE] meeting application 조회

- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
댓글 서비스 리팩토링
중복된 코드를 제거하고 검증 메소드를 생성
> [Refactor] 댓글 중복 코드 제거

- backend/src/main/java/com/app/backend/domain/chat/message/controller/MessageWebSocketController.java
- backend/src/main/java/com/app/backend/domain/chat/message/dto/request/MessageRequest.java
- backend/src/main/java/com/app/backend/domain/chat/message/dto/response/MessageResponse.java
- backend/src/main/java/com/app/backend/domain/chat/message/service/MessageService.java
- backend/src/main/java/com/app/backend/global/config/SecurityConfig.java
- backend/src/main/java/com/app/backend/global/config/WebSocketConfig.java
- backend/src/test/java/com/app/backend/domain/chat/message/controller/MessageControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/message/service/MessageServiceTest.java
- backend/src/test/java/com/app/backend/domain/chat/room/controller/ChatRoomControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/room/controller/ChatRoomMemberControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/util/TestDataUtil.java
- #90 
- 웹소켓 설정 추가, 수정
- 웹소켓 메세지 컨트롤러 추가
> [Feature]: [BE] 웹소켓 설정 및 메세지 처리

- backend/src/test/java/com/app/backend/domain/category/controller/CategoryControllerTest.java
- backend/src/test/java/com/app/backend/domain/meetingApplication/meetingApplicationControllerTest/MeetingApplicationControllerTest.java
> [FIX]: [BE] category, meetingApplication 컨트롤러 테스트 수정

- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
> [FIX]: [BE] 페이징 테스트 수정

- backend/src/test/java/com/app/backend/domain/chat/message/controller/MessageControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/room/controller/ChatRoomControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/room/controller/ChatRoomMemberControllerTest.java
- backend/src/test/java/com/app/backend/domain/chat/util/TestDataUtil.java
- #103 
- 컨트롤러 테스트에 .wit(user())로 권한 추가
> [FIX]: [BE] 채팅방 컨트롤러 테스트에 권한 추가

- backend/src/main/java/com/app/backend/domain/member/controller/KakaoController.java
- backend/src/main/java/com/app/backend/domain/member/dto/kakao/TokenDto.java
- backend/src/main/java/com/app/backend/domain/member/service/KakaoAuthService.java
- frontend/src/app/ClientPage.tsx
- frontend/src/app/oauth/callback/kakao/page.tsx
- 카카오 요청 중복 버그 수정
- 카카오 로그인 요청이 2번 되는 버그 수정
- 로그인 성공시 로그인 유저에게 보이는 메뉴 보여지도록 수정 (채팅, 모임 등)
> [Bug] : [FE] 카카오 로그인 2번 요청

- frontend/src/app/ClientLayout.tsx
- 로그인 후 새로고침 해도 상단의 메뉴 사라지지 않도록 수정
> [Bug] : [FE] 새로고침 해도 로그인 상태 유지

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/chat/ClientPage.tsx
- frontend/src/app/chat/[id]/ClientPage.tsx
- #98 
- 채팅방 접속 시 채팅방 id로 웹 소켓 연결, 메세지 전송 후 응답 메세지 바로 랜더링
- 화면 짤림 수정
- 다크모드 스타일 추가
> [Feature]: [FE] 채팅방 접속 시 웹소켓 연결, 메세지 전송

- backend/src/main/java/com/app/backend/global/init/db/DataInit.java
- "dev" 프로필 기준 BackendApplication 실행 시 관리자 계정 1개 생성/저장
- 관리자 계정이 1개 이상 존재할 경우 미생성
- 아이디: admin
- 비밀번호 : admin
* 비밀번호 암호화 적용(PasswordEncoder)
- 닉네임 : admin
* Provider는 LOCAL 설정
> [Feature]: [BE] 관리자 계정 생성/저장 클래스 추가

- backend/src/main/java/com/app/backend/global/init/db/DataInit.java
- 수정 전: equals("admin")
- 수정 후: equals("ADMIN")
-
> [FIX]: [BE] 권한 비교 조건문 수정

- backend/src/main/java/com/app/backend/global/init/db/DataInit.java
- 관리자 권한 명칭 수정: "ADMIN" -> "ROLE_ADMIN"
> [BUG]: [BE] 관리자 계정 권한 수정

- frontend/src/app/ClientLayout.tsx
- frontend/src/app/admin/ClientPage.tsx
- frontend/src/app/admin/login/ClientPage.tsx
- frontend/src/app/admin/login/page.tsx
- #114 
- 관리자 로그인 페이지 구현
- 관리자 페이지 구현
> [Feature]: [FE] 관리자 페이지, 관리자 로그인 페이지 구현

- backend/src/main/java/com/app/backend/domain/group/controller/GroupController.java
- backend/src/main/java/com/app/backend/domain/group/dto/request/GroupRequest.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupService.java
- backend/src/test/java/com/app/backend/domain/group/controller/GroupControllerTest.java
- backend/src/test/java/com/app/backend/domain/group/service/GroupServiceTest.java
- GroupService: 모임 메인 페이지에 출력할 페이징 메서드 추가
- GroupController: getGroups() 메서드 수정
- 기존: 단순 모임 목록(List) 조회
- 수정:  Search DTO 및 Pageable 파라미터 추가,  페이징 목록(Page) 조회
- GroupRequest: getGroups()용 Search 클래스(요청 DTO) 추가
- 테스트  코드 수정/추가
> [Feature]: [BE] 모임 메인 페이지에 출력할 페이징 메서드 수정/추가 등

- frontend/src/app/chat/[id]/ClientPage.tsx
- 이전 메세지 조회 기능
- 스크롤을 위로 올리면 이전 채팅 메세지 조회 가능
> [Feature] [FE] 이전 채팅 메세지 조회

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerReplyTest.java
- 대댓글 수정 기능 
- 대댓글 수정
- 테스트 코드 통과
> [Feature]: [BE] 대댓글 수정 기능

- backend/src/main/java/com/app/backend/global/annotation/CustomPageJsonSerializer.java
- backend/src/main/java/com/app/backend/global/aop/AppAspect.java
- backend/src/main/java/com/app/backend/global/config/AopConfig.java
- backend/src/main/java/com/app/backend/global/config/AppConfig.java
- backend/src/main/java/com/app/backend/global/module/CustomPageModule.java
- 스프링 부트에서 기본 제공하는 방식으로 Page 객체를 응답할 경우 프론트엔드에서 사용하지 않는 불필요한 데이터 발생 가능
- 응답 데이터의 최소화를 위해 Page를 리턴할 때 필요한 데이터만 담을 수 있도록 모듈 생성 및 컨트롤러 대상 AOP 구현
> [Feature]: [BE] Page 객체 데이터 최소화를 위한 AOP 구현

- backend/src/main/java/com/app/backend/domain/member/util/CommonUtil.java
- backend/src/main/java/com/app/backend/global/config/SecurityConfig.java
- frontend/src/app/ClientLayout.tsx
- frontend/src/app/admin/login/ClientPage.tsx
- frontend/src/stores/auth/LoginMember.tsx
- 로그아웃 서버 코드 수정
- 로그아웃시 refreshToken 담겨있는 쿠키 완전 삭제로 수정
> [Refactor] 로그아웃에서 refreshToken 삭제되도록 수정

- backend/src/main/java/com/app/backend/global/aop/AppAspect.java
- PageJsonSerializerAspect 내 직렬화 과정 수정
> [FIX]: [BE] PageJsonSerializerAspect 수정

- backend/src/main/java/com/app/backend/domain/member/controller/KakaoController.java
- backend/src/main/java/com/app/backend/domain/member/dto/kakao/TokenDto.java
- backend/src/main/java/com/app/backend/domain/member/service/KakaoAuthService.java
- frontend/src/app/ClientLayout.tsx
- frontend/src/app/ClientPage.tsx
- frontend/src/app/member/info/ClientPage.tsx
- frontend/src/app/oauth/callback/kakao/page.tsx
- 로그인 성공시 local storage 에는 access token 만 존재하도록 수정
> [Bug] 로그인 성공시 local storage 저장 데이터 수정

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerReplyTest.java
- 대댓글 삭제 기능
- 대댓글 삭제
- 테스트 코드 통과
> [Feature]: [BE] 대댓글 삭제 기능 

- backend/src/main/java/com/app/backend/global/annotation/CustomPageJsonSerializer.java
- backend/src/main/java/com/app/backend/global/aop/AppAspect.java
- backend/src/main/java/com/app/backend/global/module/CustomPageModule.java
- 스프링 기본 Page 객체 응답 시 필요/불필요 데이터 선택을 위한 AOP 수정
- 어노테이션의 파라미터를 false 또는 true로 설정함으로써 해당 값의 포함 여부를 결정
* 기본값은 모두 true
> [Feature]: [BE] CustomPageJsonSerializer 어노테이션 파라미터 추가

- backend/src/main/java/com/app/backend/domain/member/dto/response/MemberLoginResponseDto.java
- backend/src/main/java/com/app/backend/domain/member/entity/MemberDetails.java
- frontend/src/app/admin/login/ClientPage.tsx
- frontend/src/app/oauth/callback/kakao/page.tsx
- 내 정보의 가입일자 데이터 수정
- DB에 저장된 가입일자를 내 정보 조회에 반영하도록 수정
> [Bug] my info 가입일 수정

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/dto/response/CommentResponse.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepository.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerReplyTest.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
- 대댓글 조회
- 대댓글 조회 테스트 코드
- 부모 댓글이 삭제 되어도 대댓글 CRUD 가능 (추가 수정)
- 대댓글을 페이징으로 조회
- 부모 댓글이 삭제되더라도 대댓글 추가, 조회, 수정, 삭제가 가능하다.  (추가 수정)
> [Feature]: [BE] 대댓글 조회 기능 외

- backend/src/main/java/com/app/backend/global/config/SecurityConfig.java
- frontend/src/app/ClientLayout.tsx
- 로그인 세션 유지시간 표시
- 로그인 세션 유지 가능한 시간을 홈페이지 상단에 표시
- 유지시간이 끝났을 경우 자동 로그아웃
- 시간 연장 버튼을 통해 세션 유지시간 초기화
> [Feature] [FE] 메인 페이지 로그인 세션 유지시간 표시. 세션 연장 버튼 추가

- frontend/.idea/.gitignore
- frontend/.idea/frontend.iml
- frontend/.idea/inspectionProfiles/Project_Default.xml
- frontend/.idea/misc.xml
- frontend/.idea/modules.xml
- frontend/.idea/vcs.xml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/admin/ClientPage.tsx
- frontend/src/app/admin/categories/ClientPage.tsx
- frontend/src/app/admin/categories/page.tsx
- 카테고리 화면 구현(생성폼, 수정폼, 수정 삭제 버튼)
- 기본 화면
- 수정할 때
- 카테고리 수정, 삭제 전 경고 메세지 출력
- 입력값 오류는 텍스트상자 아래에 출력되게
- 디자인 수정, 다크모드 적용 추가 예정
- 카테고리 화면
> [Feat]: [FE] 카테고리 화면 구현 

- backend/build.gradle.kts
- backend/src/main/java/com/app/backend/domain/group/controller/GroupController.java
- backend/src/main/java/com/app/backend/domain/group/controller/KakaoProxyController.java
- backend/src/main/java/com/app/backend/domain/group/dto/response/GroupResponse.java
- backend/src/main/java/com/app/backend/domain/group/service/WebClientService.java
- backend/src/main/java/com/app/backend/global/config/WebClientConfig.java
- backend/src/main/resources/config/application-dev_auth.yml
- backend/src/test/java/com/app/backend/domain/group/controller/GroupControllerTest.java
- backend/src/test/resources/config/application-test_auth.yml
- frontend/src/app/groups/ClientPage.tsx
- frontend/src/app/groups/[groupId]/ClientPage.tsx
- frontend/src/app/groups/[groupId]/edit/ClientPage.tsx
- frontend/src/app/groups/[groupId]/edit/page.tsx
- frontend/src/app/groups/[groupId]/page.tsx
- frontend/src/app/groups/create/ClientPage.tsx
- frontend/src/app/groups/create/page.tsx
- frontend/src/app/groups/page.tsx
- frontend/src/components/common/Pagination.tsx
- frontend/src/components/groups/AddressSearchModal.tsx
- frontend/src/components/groups/CategorySelect.tsx
- frontend/src/components/groups/KakaoMap.tsx
- frontend/src/components/groups/KakaoMapSelector.tsx
- 모임 페이징 목록, 상세 조회 페이지 추가
- 카카오맵 API 활용
- 생성/수정 페이지 초안 추가
- 백엔드 서버를 통한 프록시 호출을 위한 WebFlux 추가
- KakaoProxyController 및 WebClientService 추가
> [Feature]: [FE/BE] 모임 목록 및 상세 조회 페이지 추가

- frontend/src/app/groups/ClientPage.tsx
- frontend/src/app/groups/[groupId]/ClientPage.tsx
- frontend/src/app/groups/[groupId]/edit/ClientPage.tsx
- frontend/src/app/groups/[groupId]/page.tsx
- frontend/src/app/groups/create/ClientPage.tsx
- 모임 메인페이지(페이징 목록), 상세 페이지 호출 시 토큰 미전달 부분 수정
> [Fix]: [FE] 모임 페이지 토큰 누락 수정

- frontend/src/components/groups/DeleteConfirmModal.tsx
> [FIX]: [FE] 모임 삭제 확인 모달 추가

- backend/src/main/java/com/app/backend/domain/group/dto/response/GroupResponse.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryImpl.java
- backend/src/main/java/com/app/backend/global/init/db/DataInit.java
- frontend/src/app/groups/ClientPage.tsx
- frontend/src/app/groups/[groupId]/ClientPage.tsx
- frontend/src/components/groups/KakaoMapMultiMarker.tsx
> [Feature]: [FE/BE] 모임 신청 관리 페이지 추가 등

- backend/src/main/java/com/app/backend/global/init/db/DataInit.java
> [FIX]: [BE] 회원 더미데이터 오류 수정

- backend/src/main/java/com/app/backend/domain/chat/message/controller/MessageWebSocketController.java
- backend/src/main/java/com/app/backend/global/config/RedisConfig.java
- backend/src/main/java/com/app/backend/global/redis/service/RedisPublisher.java
- backend/src/main/java/com/app/backend/global/redis/service/RedisSubscriber.java
- backend/src/test/java/com/app/backend/domain/chat/message/RedisPubSubTest.java
- #177 
- Redis Pub/Sub 적용
- 메세지 전송 플로우
- 웹소켓으로 메세지 전송 -> 컨트롤러에서 레디스로 메세지 발행 -> 레디스 서버에서 수신확인 -> onMessage 메서드 호출 -> 웹소켓으로 브로드 캐스트 -> 프론트
> [Feature] [BE] Redis Pub/Sub 적용

- backend/src/main/java/com/app/backend/domain/group/dto/response/GroupResponse.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/controller/MeetingApplicationController.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/dto/response/MeetingApplicationResponse.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/service/MeetingApplicationService.java
- frontend/src/app/groups/ClientPage.tsx
- frontend/src/app/groups/[groupId]/ClientPage.tsx
- frontend/src/app/groups/[groupId]/edit/page.tsx
- frontend/src/app/groups/[groupId]/meeting_applications/ClientPage.tsx
- frontend/src/app/groups/[groupId]/meeting_applications/[meetingApplicationId]/ClientPage.tsx
- frontend/src/app/groups/[groupId]/meeting_applications/[meetingApplicationId]/page.tsx
- frontend/src/app/groups/[groupId]/meeting_applications/page.tsx
- frontend/src/components/common/ConfirmModal.tsx
- frontend/src/components/groups/GroupCard.tsx
- frontend/src/components/groups/KakaoMapMultiMarker.tsx
> [FIX]: [FE/BE] 커밋 누락 복구

- frontend/Dockerfile
- frontend/src/app/ClientLayout.tsx
> bug : 새로고침해도 로그인 안풀리게 수정

- frontend/.gitignore
- frontend/process.env
- frontend/src/app/groups/[groupId]/post/[postId]/page.tsx
> [FIX]: [FE] .gitignore 수정

- backend/src/main/java/com/app/backend/domain/group/controller/GroupController.java
- backend/src/main/java/com/app/backend/domain/group/dto/response/GroupResponse.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupMembershipService.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupService.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/entity/MeetingApplication.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/repository/MeetingApplicationRepository.java
- backend/src/main/java/com/app/backend/domain/meetingApplication/service/MeetingApplicationService.java
- backend/src/test/java/com/app/backend/domain/group/controller/GroupControllerTest.java
- frontend/src/app/groups/[groupId]/ClientPage.tsx
- frontend/src/app/groups/[groupId]/meeting_applications/ClientPage.tsx
- 모임 가입 신청 상태에서 신청 중복을 위해 모임 가입 버튼 비활성화
- 관련 DTO 수정
> [Feature]: [FE/BE] 모임 가입 신청 중복 방지 구현

- frontend/src/app/chat/[id]/ClientPage.tsx
- #191 
- 메세지 줄바뀜 문제 해결
- 배경 max-w 속성 100% 로 수정
> [FIX]: [FE] 메세지 배경 max-w 속성 100% 로 수정

- frontend/src/app/groups/[groupId]/post/[postId]/page.tsx
- router.push 를 router.back 으로 수정
ISSUE #192
> [Fix]: [FE] 뒤로가기 활성화

- backend/src/main/java/com/app/backend/domain/comment/entity/Comment.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerReplyTest.java
- 답글 삭제시 답글 카운트가 변경되지 않았음.
- 삭제하면 삭제된 답글을 제외하고 카운트되도록 수정
- 삭제하고 **새로고침**해야 카운트가 변경됨
- 삭제하면 삭제된 답글을 제외하고 카운트되도록 수정
> [Bug] 답글 삭제 시 답글 카운트 변경

- backend/src/main/java/com/app/backend/domain/group/dto/response/GroupMembershipResponse.java
- backend/src/main/java/com/app/backend/domain/member/controller/ApiMemberController.java
- backend/src/main/java/com/app/backend/domain/member/service/MemberService.java
- frontend/src/app/groups/ClientPage.tsx
- frontend/src/app/member/info/ClientPage.tsx
- 내 정보에 모임 관련 정보 표기
- 모임 가입 멤버십 상태 표기 및 클릭 시 해당 모임 상세 페이지 로딩
> [Feature]: [FE] 내 정보에 모임 가입/가입 신청 정보 표기

- frontend/src/api/comment/commentApi.ts
- frontend/src/app/groups/[groupId]/post/[postId]/CommentItem.tsx
- frontend/src/app/groups/[groupId]/post/[postId]/CommentList.tsx
- frontend/src/app/groups/[groupId]/post/[postId]/page.tsx
- 댓글 , 답글 sort 수정 & 답글 수 반영
ISSUE #199
> [Fix]: [FE] 댓글 , 답글 sort 수정 & 답글 수 반영

- backend/src/main/java/com/app/backend/domain/group/controller/GroupController.java
- backend/src/main/java/com/app/backend/domain/group/dto/request/GroupRequest.java
- backend/src/main/java/com/app/backend/domain/group/entity/Group.java
- backend/src/main/java/com/app/backend/domain/group/entity/RecruitStatus.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryCustom.java
- backend/src/main/java/com/app/backend/domain/group/repository/GroupRepositoryImpl.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupMembershipService.java
- backend/src/main/java/com/app/backend/domain/group/service/GroupService.java
- backend/src/test/java/com/app/backend/domain/group/controller/GroupControllerTest.java
- backend/src/test/java/com/app/backend/domain/group/repository/GroupRepositoryTest.java
- backend/src/test/java/com/app/backend/domain/group/service/GroupServiceTest.java
- frontend/src/app/groups/ClientPage.tsx
- frontend/src/app/groups/[groupId]/ClientPage.tsx
- frontend/src/app/groups/[groupId]/meeting_applications/ClientPage.tsx
- 모임 모집 상태 로직 추가
- 모임 최대 모집 인원과 모임 가입 인원 비교에 따라 모집 상태 변경
- 모임 관리자가 모임 모집 상태를 강제로 닫은 경우 대비 boolean 필드 추가
- 모임 검색 페이지에 모집 상태에 따른 검색 추가
- 모임 상세 페이지에 모임 상태에 따라 모집 신청 버튼 활성화/비활성화
> [Feature]: [FE/BE] 모임 모집 상태 관련 로직 추가 등

- backend/src/main/java/com/app/backend/domain/comment/controller/CommentController.java
- backend/src/main/java/com/app/backend/domain/comment/dto/response/CommentResponse.java
- backend/src/main/java/com/app/backend/domain/comment/entity/CommentLike.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentLikeRepository.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepository.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepositoryCustom.java
- backend/src/main/java/com/app/backend/domain/comment/repository/CommentRepositoryImpl.java
- backend/src/main/java/com/app/backend/domain/comment/service/CommentService.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentControllerTest.java
- backend/src/test/java/com/app/backend/domain/comment/controller/CommentLikeControllerTest.java
- 댓글 좋아요
- 쿼리 dsl
- 테스트 코드
- 댓글 좋아요 기능
- 정합성을 고려함
- 댓글 조회시 좋아요 수도 같이 조회되도록 쿼리 dsl을 사용함
- 테스트 코드 추가
> [Feature]: [BE] 댓글 좋아요 

- backend/src/main/java/com/app/backend/domain/group/repository/GroupLikeRepository.java
- backend/src/test/java/com/app/backend/domain/group/service/GroupLikeServiceTest.java
> [Refactor}: [BE] GroupLikeRepository 수정
